export const tweetPosts = [
  {
    id: 0,
    name: "Doctor Strange",
    handlerName: "@drstrange",
    organization: "The university of America",
    tweetText:
      "I am the Marvelous . ",
    tweetPic:
      "https://i.insider.com/6262ff239f65660019064d73?width=1000&format=jpeg&auto=webp",
    tweetCount: 100,
    retweetCount: 100,
    likesCount: 100,
    tweetComment: [],
    isOpen: false,
    inrDcr: false,
    color: "rgb(60,60,60)",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        id: 0,
        tweetText:
          "I am everything the dr,the engineer etc. ",
        tweetPic:
          "https://giffiles.alphacoders.com/214/214285.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText:
          "Human world ",
        tweetPic:
          "https://media.tenor.com/04qbpHO1mJkAAAAC/dr-strange-doctor-strange.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,

        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 1,
    name: "Lucky ALi",
    handlerName: "@luckyali",
    organization: "",
    tweetText:
      "For someone to live another has to die. That is wildlife. My shot that was featured in NatGeo. Shot using @NikonIndia gear.",
    tweetPic:
      "https://media.kulfyapp.com/0UY69O/0UY69O-360.gif",
    tweetCount: 200,
    retweetCount: 200,
    likesCount: 200,
    tweetComment: [],
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "10k",
    hastags: ["#wildLife", "#photoGraphy"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
        tweetPic:
          "https://media.kulfyapp.com/0UY69O/0UY69O-360.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
        tweetPic:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcspQfyJHGWHztlng2V7323CSTk5UumAx0eA&usqp=CAU",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Malvika Sharma",
    handlerName: "@Malvikasharma123",
    organization: "",
    tweetText: "Earned..Not Given.",
    tweetPic:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuliSpiQ5RtPESdIgED0yMacvdQ_j8dFLKIg&usqp=CAU",
    tweetCount: 700,
    retweetCount: 700,
    likesCount: 900,
    tweetComment: [],
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "100k",
    refLink: "https://www.globalwildlife.org/blog/",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Indian actress and model ",
        tweetPic:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuliSpiQ5RtPESdIgED0yMacvdQ_j8dFLKIg&usqp=CAU",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText:
          "Hi there all",
        tweetPic:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuliSpiQ5RtPESdIgED0yMacvdQ_j8dFLKIg&usqp=CAU",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Alu Arjun",
    handlerName: "@alluarjun",
    organization: "",
    tweetText: "Stolen.. Not earned.",
    tweetPic:
      "https://media.tenor.com/k60eaGkHoBkAAAAd/pushpa-the-rise-allu-arjun.gif",

    tweetCount: 400,
    retweetCount: 327,
    likesCount: 90,
    tweetComment: "3",
    tweetComment: [],
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "7k",
    hastags: ["#sports", "#Winners"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Mein jhukega nhi saala ",
        tweetPic:
          "https://media.tenor.com/k60eaGkHoBkAAAAd/pushpa-the-rise-allu-arjun.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText:
          "The dream is yet to be achieved",
        tweetPic:
          "https://cdn.vox-cdn.com/thumbor/eRf33r_m-6LLevsVbxeGVuwleM4=/0x41:800x491/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/49522613/bill-gates-ask-me-anything.0.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Arijit Singh",
    handlerName: "@arijitsingh@13",
    organization: "",
    tweetText: "Koi lamha mera na ho tere bina ",
    tweetPic:
      "https://media.tenor.com/LNa0IAC-fN8AAAAC/arijit-singh-arijit.gif",
    tweetCount: 650,
    retweetCount: 699,
    likesCount: 900,
    tweetComment: [],
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "17k",
    hastags: ["#HockeyLover", "#Hockey", "#Team India"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Koi lamha mera na ho tere bina",
        tweetPic: "https://media.tenor.com/LNa0IAC-fN8AAAAC/arijit-singh-arijit.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText:
          "Koi lamha mera na ho tere bina ",
        tweetPic: "https://pbs.twimg.com/media/FUlso_uVsAAP0jx.jpg:large",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "BGMI",
    handlerName: "@bgmiIndia",
    organization: "",
    tweetText: `Welcome to Bgmi`,
    tweetPic:
      "https://media1.giphy.com/media/KwY3NuWKRM3aUrAaCK/200w.gif?cid=82a1493byu8hiqu2zzhek888n0b5mjrtxsk6enrv43fsjxay&rid=200w.gif&ct=g",
    tweetCount: 650,
    retweetCount: 699,
    likesCount: 900,
    tweetComment: [],
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "17k",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Welcome to bgmi",
        tweetPic:
          "https://media1.giphy.com/media/KwY3NuWKRM3aUrAaCK/200w.gif?cid=82a1493byu8hiqu2zzhek888n0b5mjrtxsk6enrv43fsjxay&rid=200w.gif&ct=g",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
      {
        tweetText:
          "Heyy there",
        tweetPic:
          "https://media1.giphy.com/media/KwY3NuWKRM3aUrAaCK/200w.gif?cid=82a1493byu8hiqu2zzhek888n0b5mjrtxsk6enrv43fsjxay&rid=200w.gif&ct=g",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "ram",
            handlerName: "ram@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
          {
            name: "sham",
            handlerName: "sham@gmail.com",
            tweetReplyText: "hello everyone",
            tweetCount: 100,
            retweetCount: 100,
            likesCount: 100,
            viewsCount: "102k",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Goku the Saiyan",
    handlerName: "@supersaiyan",
    organization: "",
    tweetText: `Ultra Intinct`,
    tweetPic:
      "https://thumbs.gfycat.com/ElaborateEnragedBedlingtonterrier-size_restricted.gif",
    tweetCount: 100,
    retweetCount: 509,
    likesCount: 450,
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "79k",
    hastags: ["#Freedom Fighter", "#India"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Ultra Instinct ",
        tweetPic:
          "https://thumbs.gfycat.com/ElaborateEnragedBedlingtonterrier-size_restricted.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText:
          "Ultra Instinct ",
        tweetPic:
          "https://thumbs.gfycat.com/ElaborateEnragedBedlingtonterrier-size_restricted.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 7,
    name: "Naruto Uzumaki",
    handlerName: "@narutouzumaki",
    organization: "",
    tweetText: `Nothing to fear`,
    tweetPic:
      "https://giffiles.alphacoders.com/155/15591.gif",
    tweetCount: 100,
    retweetCount: 509,
    likesCount: 450,
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "79k",
    refLink: "https://twitter.com/AshwiniVaishnaw",
    hastags: ["#Electronics", "#iphone"],
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Naruto Uzumaki",
        tweetPic:
          "https://giffiles.alphacoders.com/155/15591.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText:
          "Heyy",
        tweetPic:
          "https://giffiles.alphacoders.com/155/15591.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 8,
    name: "Jass Manak",
    handlerName: "@jassmanak",
    organization: "",
    tweetText: `Har sa utte naam bole tera`,
    tweetPic:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIoyXyT4rJ-s8byW03VLIx-WDxbl_nABtwvA&usqp=CAU",
    tweetCount: 10,
    retweetCount: 50,
    likesCount: 40,
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "9k",
    hastags: ["#bcm112", "#students", "#education", "#allGovernmets"],
    refLink: "https://twitter.com/ippittipapitti",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Hweyyw ",
        tweetPic:
          "https://media.tenor.com/AO5U1y9g3U4AAAAC/jass-manak-jass.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText:
          "Lucknow i am back",
        tweetPic:
          "https://media.tenor.com/AO5U1y9g3U4AAAAC/jass-manak-jass.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 9,
    name: "Lionel Messi",
    handlerName: "@messi9",
    organization: "Qatar",
    tweetText:
      "Goallll",
    tweetPic:
      "https://thumbs.gfycat.com/DirtyUnnaturalHoopoe-max-1mb.gif",
    tweetCount: 10,
    retweetCount: 50,
    likesCount: 40,
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "9k",
    hastags: ["#Sports", "#Footbal"],
    refLink: "https://dainik-b.in/ekPIEaD5Jwb",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Heyy Dubai",
        tweetPic:
          "https://thumbs.gfycat.com/DirtyUnnaturalHoopoe-max-1mb.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText:
          "Heyy ",
        tweetPic:
          "https://thumbs.gfycat.com/DirtyUnnaturalHoopoe-max-1mb.gif",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
  {
    id: 10,
    name: "Suryakumar Yadav",
    handlerName: "@sky",
    organization: "Bcci",
    tweetText:
      "Cricket is Love",
    tweetPic:
      "https://static.ffx.io/images/$zoom_3.3093749999999997%2C$multiply_0.7554%2C$ratio_1.776846%2C$width_1059%2C$x_0%2C$y_341/t_crop_custom/q_86%2Cf_auto/81683f159f16c8ed0b0b90a9d0c6901525e509eb",
    retweetCount: 50,
    likesCount: 40,
    inrDcr: false,
    color: "rgb(60,60,60)",
    viewsCount: "9k",
    hastags: ["#BIGcat", "#HeartofIndia"],
    refLink: "https://www.mptigerfoundation.org/news-corner/blog",
    followers: 200,
    followings: 400,
    joinedDate: "22 dec 2022",
    tweets: [
      {
        tweetText:
          "Worldcup",
        tweetPic:
          "https://static.ffx.io/images/$zoom_3.3093749999999997%2C$multiply_0.7554%2C$ratio_1.776846%2C$width_1059%2C$x_0%2C$y_341/t_crop_custom/q_86%2Cf_auto/81683f159f16c8ed0b0b90a9d0c6901525e509eb",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
      {
        tweetText:
          "Sixer Yess ",
        tweetPic:
          "https://static.ffx.io/images/$zoom_3.3093749999999997%2C$multiply_0.7554%2C$ratio_1.776846%2C$width_1059%2C$x_0%2C$y_341/t_crop_custom/q_86%2Cf_auto/81683f159f16c8ed0b0b90a9d0c6901525e509eb",
        tweetCount: 100,
        retweetCount: 100,
        likesCount: 100,
        viewsCount: "102k",
        TweetReplies: [
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
          {
            name: "",
            handlerName: "",
            tweetReplyText: "",
          },
        ],
      },
    ],
  },
];
